### ISSUE TITLE
同学 你L-GRE-GRE核心词汇助记与精练第2版.pdf 我下载下来好像是坏的。 

### ISSUE THREAD

**Issue by cwang365** [LER0ever/GRE-CN#1]
同学 你L-GRE-GRE核心词汇助记与精练第2版.pdf 我下载下来好像是坏的。

**Comment by LER0ever** [comment]
@cwang365 你好，是这样的...Github对LFS的大小和流量有限制，下载的人多了之后这个月的Quota已经用完了，然后Github就会禁止访问这个lfs的文件。目前我也没有办法，之后可能会转到GitLab上托管或者 Gitlab也有限制的话会用我自己的 https://code.rongyi.io

**Comment by LER0ever** [comment]
如果你现在非常需要的话可以到这个DropBox链接: https://www.dropbox.com/sh/5xjpkujuwloaatp/AAC_T2M52SMEoT9vRkhN9MR_a?dl=0
上面下，里面是和这个Repo一样的文件。

**Comment by cwang365** [comment]
谢谢啦。 祝考研顺利！
